In [4]:
import numpy as np
import pandas as pd

a = np.array([1, 2, 3, 2, 3, 4, 3, 4, 5, 6])
b = np.array([7, 2, 10, 2, 7, 4, 9, 4, 9, 8])
c = []

for i in range (len(a)):
  for y in range (len(b)):
    if a[i] == b[y]:
      c.append(b[y])
c = list(dict.fromkeys(c))
print(c)
print('\n')

fiveByThree = np.array([1, 6, 11])
for i in range (1,5):
  newRow = [i + 1, i + 6, i + 11]
  fiveByThree = np.vstack([fiveByThree, newRow])
print(fiveByThree)
print('\n')

result = np.sort(fiveByThree.ravel())
print(result)
print('\n')

newarr = (fiveByThree.reshape(5, 1, 3)).T
print(newarr)
print('\n')

newarr2 = (newarr.reshape(3,5)).T
print(newarr2)
print('\n')

d = np.array([12, 5, 7, 15, 3, 1, 8])
e = np.array([14, 6, 3, 11, 19, 12, 5])
d = list(set(d) - set(e))
print(d)

print("\n48134.1 is the maximum yearly NYC consumption of water")
print("38 calendar years are represented in this data set")
print("160.3076923 is the mean for the per capita daily water consumption")

[2, 4]


[[ 1  6 11]
 [ 2  7 12]
 [ 3  8 13]
 [ 4  9 14]
 [ 5 10 15]]


[ 1  2  3  4  5  6  7  8  9 10 11 12 13 14 15]


[[[ 1  2  3  4  5]]

 [[ 6  7  8  9 10]]

 [[11 12 13 14 15]]]


[[ 1  6 11]
 [ 2  7 12]
 [ 3  8 13]
 [ 4  9 14]
 [ 5 10 15]]


[8, 1, 15, 7]

48134.1 is the maximum yearly NYC consumption of water
38 calendar years are represented in this data set
160.3076923 is the mean for the per capita daily water consumption


Sources used: 
https://www.w3schools.com/python/python_howto_remove_duplicates.asp
https://www.codegrepper.com/code-examples/python/python+append+row+to+2d+array
https://www.geeksforgeeks.org/python-flatten-a-2d-numpy-array-into-1d-array/
https://numpy.org/doc/stable/reference/generated/numpy.sort.html
https://www.w3schools.com/python/numpy/numpy_array_sort.asp
https://www.w3schools.com/python/numpy/numpy_array_reshape.asp
https://stackoverflow.com/questions/50635960/iterate-through-a-list-compare-values-and-remove-duplicate-python